FASTBOOT: Fix warning introduced in recent change
Warning was:

cmd_fastboot.c: In function 'fbt_handle_flash':
cmd_fastboot.c:1648: error: pointer targets in passing argument 2 of 'himport_r' differ in signedness
/usr/local/disk2/mjchen/git/u-boots/include/search.h:96: note: expected 'const char *' but argument is of type 'const unsigned char *'

Change-Id: I37c877cf78c0a739d2047b66d820db1bc897d1a7
Signed-off-by: Mike J. Chen <mjchen@google.com>